# version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:latest
    build: .
    command: sh -c "bundle install && bundle exec jekyll serve --host 0.0.0.0 --watch --force_polling"
    ports:
      - 8080:4000
      - 35729:35729
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
